# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        files: ^src/
        args:
          - --fix
          - --unsafe-fixes
      - id: ruff-format
        files: ^src/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        files: ^src/rs3_study_curvature/(cli/|analysis/(stats\.py|report\.py)|viz/plots\.py)
        args:
          - --ignore-missing-imports
          - --namespace-packages
          - --no-warn-no-return
          - --follow-imports=silent
        additional_dependencies:
          - pandas-stubs
          - types-PyYAML
          - types-tqdm
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        exclude: ^configs/class_map\.yml$
      - id: check-toml

exclude: |
  (?x)^(
    src/rs3_study_curvature\.egg-info/|
    dist/|build/|\.venv/|\.tox/|
    \.pytest_cache/|\.mypy_cache/|\.ruff_cache/
  )
